# Generated by Django 5.2.6 on 2025-09-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_basicuserprofile_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='full_name',
            field=models.CharField(default='کاربر <django.db.models.fields.AutoField>', max_length=100),
        ),
    ]
