# Generated by Django 5.2.6 on 2025-09-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_alter_topic_name'),
        ('home', '0008_tweet_tweet_comment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='topic',
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic',
            field=models.ManyToManyField(blank=True, to='hashtag.topic'),
        ),
    ]
