# Generated by Django 5.2.6 on 2025-09-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_tweet_topic_tweet_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='topic',
            new_name='topics',
        ),
    ]
